/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myPanel;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import myPhoto.Photo;



/**
 *
 * @author admin
 */
public class PhotoPanel extends javax.swing.JPanel {

    /**
     * Creates new form PhotoPanel
     */
    Photo photo;
    Image image;
    
    
    
    public PhotoPanel() 
    {
        initComponents();
        setBackground(Color.GRAY); 
    }
    
    public PhotoPanel(Photo photo)
    {
        this();
        this.photo = photo;
        
    }
    
    public void setImagePanel(Image image) 
    {
        this.image = image;
    }
    
   /* public void paintComponent(Graphics g)
    {
        super.paintComponent(g);
        if(photo!=null)
            g.drawImage(photo.getSuitImage(),0,0,photo.getPhotoWidth(),photo.getPhotoHeight(),this);
        /**
         * 注意
         */
        /**if(photo!=null)
            photo.displayAll(g);**/
     //}
    
    public void paint(Graphics g)
    {
        super.paint(g);
        if(photo != null)
        {
            g.drawImage(photo.getSuitImage(),(this.getWidth()-photo.getPhotoWidth())/2,(this.getHeight()-photo.getPhotoHeight())/2,photo.getPhotoWidth(),photo.getPhotoHeight(),this);
        }
    }
    
    public void show(Photo photo)
    {
        if(photo.getSuitImage() != null)
        {
            this.photo = photo;
            repaint();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    /*public void add(Photo photo) {
        this.image = photo.getSuitImage();
    }*/


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
